---
apiVersion: enroute.saaras.io/v1
kind: RouteFilter
metadata:
  labels:
    app: {{ .Values.service.name }}-app
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-outlierdetection
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-outlierdetection
  type: route_filter_outlierdetection
  routeFilterConfig:
    config: |
          {
                "consecutive_5xx" : {{ .Values.filters.outlierdetection.consecutive5xx | int }},
                "enforcing_consecutive_5xx" : {{ .Values.filters.outlierdetection.enforcingConsecutive5xx | int }},
                "consecutive_gateway_failure" : {{ .Values.filters.outlierdetection.consecutiveGatewayFailure | int }},
                "enforcing_consecutive_gateway_failure" : {{ .Values.filters.outlierdetection.enforcingConsecutiveGatewayFailure | int }}
          }