---
apiVersion: enroute.saaras.io/v1
kind: HttpFilter
metadata:
  labels:
    app: {{ .Values.service.name }}-app
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-corsfilter
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-corsfilter
  type: http_filter_cors
  httpFilterConfig:
    config: |
         {
             "match_condition" : {
               "regex" : "\\*"
             },
             "access_control_allow_methods" : "GET, OPTIONS",
             "access_control_allow_headers" : "Content-Type",
             "access_control_expose_headers" : "*",
             "access_control_max_age" : "120"
         }