---
apiVersion: enroute.saaras.io/v1
kind: RouteFilter
metadata:
  labels:
    app: {{ .Values.service.name }}-app
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-circuitbreakers
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-circuitbreakers
  type: route_filter_circuitbreakers
  routeFilterConfig:
    config: |
          {
                "max_connections" : {{ .Values.filters.circuitbreakers.maxConnections | int }},
                "max_pending_requests" : {{ .Values.filters.circuitbreakers.maxPendingRequests | int }},
                "max_requests" : {{ .Values.filters.circuitbreakers.maxRequests | int }},
                "max_retries" : {{ .Values.filters.circuitbreakers.maxRetries | int }}
          }