---
apiVersion: enroute.saaras.io/v1
kind: HttpFilter
metadata:
  labels:
    app: {{ .Values.service.name }}-app
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-jwtfilter
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-jwtfilter
  type: http_filter_jwt
  services:
     name: {{ .Values.service.name }}-{{ .Values.service.port }}-externalauth
     port: 443
     protocol: tls
  httpFilterConfig:
    config: |
         {
           "name" : {{ .Values.filters.jwt.name | quote }},
           "jwks_uri" : {{ .Values.filters.jwt.jwksUri | quote }},
           "audience" : {{ .Values.filters.jwt.audience | quote }},
           "issuer" : {{ .Values.filters.jwt.issuer | quote }},
           "route" : [
             {{- range .Values.filters.jwt.routes }}
             {"prefix" : {{ .prefix | quote }}}
             {{- end }}
           ],
           "jwt_service_name" : {{ .Values.filters.jwt.serviceName | quote }},
           "jwt_service_port" : {{ .Values.filters.jwt.servicePort | int }},
           "jwt_forward_header_name" : {{ .Values.filters.jwt.headerName | quote }}
         }