---
apiVersion: enroute.saaras.io/v1
kind: HttpFilter
metadata:
  labels:
    app: {{ .Values.service.name }}-app
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-corsfilter
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-corsfilter
  type: http_filter_cors
  httpFilterConfig:
    config: |
         {
             "match_condition" : {
               "regex" : {{ .Values.filters.cors.regex | quote }}
             },
             "access_control_allow_methods" : {{ join "," .Values.filters.cors.allowMethods | quote }},
             "access_control_allow_headers" : {{ join "," .Values.filters.cors.allowHeaders | quote }},
             "access_control_expose_headers" : {{ .Values.filters.cors.exposeHeaders | quote }},
             "access_control_max_age" : {{ .Values.filters.cors.maxAge | int | quote }}
         }