---
apiVersion: enroute.saaras.io/v1
kind: RouteFilter
metadata:
  labels:
    app: {{ .Values.service.name }}-app
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-rl2
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-rl2
  type: route_filter_ratelimit
  routeFilterConfig:
    config: |
          {
            "descriptors" :
            [
              { "request_headers": { "header_name": "x-forwarded-for", "descriptor_key": "x-forwarded-for" } },
              { "request_headers": { "header_name": "x-forwarded-proto", "descriptor_key": "x-forwarded-proto" } },
              { "generic_key": { "descriptor_value" : "default_route" } }
            ]
          }